- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars: 
    subnetid: subnet-0fa1ef45d6ebb9c04
    sgid: "sg-0a1c366ef24b32703"
    #instanttype: "t2.micro"
    image: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{item}}"
      vpc_subnet_id: "{{subnetid}}"
      instance_type: "t2.micro"
      security_group: "{{sgid}}"
      image_id: "{{image}}"
    loop: "{{instances}}"
    register: ec2_instances