- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars: 
    subnetid: subnet-0fa1ef45d6ebb9c04
    sgid: "sg-0a1c366ef24b32703"
    #instanttype: "t2.micro"
    image: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
    zone : akdevops.site
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{item}}"
      vpc_subnet_id: "{{subnetid}}"
      instance_type: "t2.micro"
      security_group: "{{sgid}}"
      image_id: "{{image}}"
    loop: "{{instances}}"
    register: ec2_instances

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ec2_instances}}"

#private ip's
  - name: create r53 private ip records
    amazon.aws.route53:
      state: present
      zone: "{{zone}}"
      record: "{{item.item}}.{{zone}}"
      type: A
      ttl: 1
      value: "{{item.instances[0].private_ip_address}}"
      wait: true
      overwrite: true
    loop: "{{ec2_instances.results}}"


#public ip
  - name: create r53 public ip records for frontend
    amazon.aws.route53:
      state: present
      zone: "{{zone}}"
      record: "{{item.item}}.{{zone}}" #front.akdevops.site
      type: A
      ttl: 1
      value: "{{item.instances[0].public_ip_address}}"
      wait: true
      overwrite: true
    loop: "{{ec2_instances.results}}"
    when: item.item == "frontend"